In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Pokemon.csv")
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [3]:
data.sort_values(["HP","Attack","Defense"])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,236,1,90,45,30,30,40,3,False
55,50,Diglett,Ground,NaN,265,10,55,25,35,45,95,1,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
381,349,Feebas,Water,NaN,200,20,15,20,10,55,80,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,594,Alomomola,Water,NaN,470,165,75,80,40,45,65,5,False
351,321,Wailord,Water,NaN,500,170,90,45,90,45,60,3,False
217,202,Wobbuffet,Psychic,NaN,405,190,33,58,33,58,33,2,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False

In [13]:
  Speed_mean = data["Speed"].mean()
    
def set_Speed(val):
    if val < Speed_mean:
        return "Speed Low"
    elif val == Speed_mean:
        return "Speed neutral"
    else:
        return "Speed High"

In [14]:
# "Speed_high_low"  -> "Speed High" , "Speed Low"
data["Speed_high_low"] = data["Speed"].apply(set_Speed)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Speed_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Speed Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Speed Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Speed High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Speed High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Speed Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Speed Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Speed High
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Speed High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Speed High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Speed High

In [28]:
  HP_mean = data["HP"].mean()
     
def set_HP(val):
    if val < HP_mean:
        return "HP Low"
    elif val == HP_mean:
        return "HP neutral"
    else:
        return "HP High"

In [29]:
# "HP_high_low"  -> "HP High" , "HP Low"
data["HP_high_low"] = data["HP"].apply(set_HP)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Speed_high_low,HP_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Speed Low,HP Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Speed Low,HP Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Speed High,HP High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Speed High,HP High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Speed Low,HP Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Speed Low,HP Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Speed High,HP Low
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Speed High,HP High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Speed High,HP High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Speed High,HP High